
name: Build Windows

on: [pull_request, push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get Submodules
      run: git submodule update --init
    
    - name: Setup CMake
      run: cmake .
      
    - name: Build
      run: cmake --build . --config ${{env.BUILD_TYPE}}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{env.BUILD_TYPE}}/copypath.exe
        generate_release_notes: true
        token: ${{ secrets.RELEASE_ACCESS_TOKEN }}
